version: '3.8'

services:
  wg-easy:
    image: weejewel/wg-easy:latest
    container_name: wg-easy-west
    environment:
      - WG_HOST=${WG_HOST_WEST}
      - PASSWORD=${WG_PASSWORD}
      - WG_PORT=51820
      - WG_DEFAULT_ADDRESS=10.2.0.x
      - WG_DEFAULT_DNS=10.2.0.2
      - WG_MTU=1420
      - WG_ALLOWED_IPS=0.0.0.0/0
      - WG_PERSISTENT_KEEPALIVE=25
    volumes:
      - ./wg-easy:/etc/wireguard
      - ../../peers:/peers
    ports:
      - "51820:51820/udp"
      - "443:51821/tcp"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
    networks:
      vpn_net:
        ipv4_address: 10.2.0.1

  adguard:
    image: adguard/adguardhome:latest
    container_name: adguard-west
    volumes:
      - ./adguard/work:/opt/adguardhome/work
      - ./adguard/conf:/opt/adguardhome/conf
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "3000:3000/tcp"
    restart: unless-stopped
    networks:
      vpn_net:
        ipv4_address: 10.2.0.2
    depends_on:
      - unbound

  unbound:
    image: mvance/unbound:latest
    container_name: unbound-west
    volumes:
      - ./unbound:/opt/unbound/etc/unbound
    restart: unless-stopped
    networks:
      vpn_net:
        ipv4_address: 10.2.0.3

networks:
  vpn_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.2.0.0/24
